apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-nginx
spec:
  revisionHistoryLimit: 30
  selector:
    matchLabels:
      app: cc-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: cc-nginx
    spec:
      containers:
      - name: cc-nginx
        image: {{ .Values.image }}
      command:
        - sleep
        - "3600"
      
