apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx_{{ .Values.name }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx_{{ .Values.name }}
  replicas: 8
  template:
    metadata:
      labels:
        app: nginx_{{ .Values.name }}
    spec:
      containers:
      - name: nginx_{{ .Values.name }}
        image: nginx