apiVersion: v1
kind: Service
metadata:
  name: nginx_service
  labels:
    app: nginx_service
spec:
  type: ClusterIP
  selector:
    app: nginx_{{ .Values.name }}
  ports:
  - port: 8080
    targetPort: 80

