apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cc-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: nginx

